### ISSUE TITLE
Showing/Hiding sub-levels does not load/save actors within them

### ISSUE THREAD

**Issue by mat414** [PipeRift/SaveExtension#13]
**Describe the bug**
When a sub-level is loaded/unloaded via streaming volume or in general, the actors within the sub-levels are not saved and loaded.

**To Reproduce**
1. Create new project from fps template.
2. Enable saving/loading of streaming levels.
3. Create a saveable actor that can be moved via physics.
4. Create a new sub-level and setup a level streaming volume to load said level.
5. Place one of our custom actors within the sub-level.
6. Play the game, enter the sub-level, move the actor, then exit and re-enter to see if the actor reset to its initial level position upon load.

**Logs**
Snippet from one of the logs when leaving and entering a sub-level.
[2019.01.17-01.43.53:983][801]LogSaveExtension: SE: Finished Serializing level
[2019.01.17-01.43.57:654][ 20]LogSaveExtension: SE: Level '/Game/Alchemy/Levels/Interiors/UEDPIE_0_PlayerHouse'
[2019.01.17-01.43.57:654][ 20]LogSaveExtension: SE: Finished Loading

**Environment**
 - Engine Version: Observed on 4.20.3 and 4.21.1
 - Plugin Version: 1.1a
 - OS: Windows 10

**Comment by muit** [comment]
Hi @mat414, 
Thank you very much for your detailed report.

I will give it a look soon and try to fix it for 1.2
Thanks

**Comment by muit** [comment]
Hi @mat414 ,

The title and the description are quite contradictory.

Levels can be loaded, shown, unloaded or hidden.
Save Extension only saves and loads(automatically) when the level is saved and loaded and not when shown or hidden.

So just to confirm, is your problem related with loading/unloading or showing/hiding?

**Comment by muit** [comment]
I have tried to reproduce this issue but everything seems to be fine on my side.
Could I ask for a test project?

**Comment by ReiMari** [comment]
I've also encountered this and made a small test project in which the issue is present. It can be downloaded here: https://mega.nz/#!0SBw2IDY!Bnr5ga6mpY7UUA6F4l7qWou6QBNT6CMsNtmQ-i4IkmY I can also make a temporary Git repo if you don't want to open a mega link and a zip file.

Unreal version: 4.21.2  
Plugin version: 1.1a

**Steps to reproduce**
1. Open the map in `Content/Case_RootLevels_StreamSwap/` called `root_stream_persistent` in the editor
2. Enter PIE
3. Click the square a couple of times to increment it's counter
4. Hit `Q` to save (seems to have no effect on behaviour that follows though)
5. Hit `B` to unload `root_stream_a` and load `root_stream_b`
6. Hit `A` to go back to `root_stream_a`

The counter on the cube actor is now back at 0 while from the documentation (the Level Streaming and World Composition section specifically) it seems like the counter should have been restored to whatever value it had before transitioning.

The maps in `Case_RootLevels_Open` show similar behaviour (reproduction steps are the same, but can be started from either map), but I'm not sure if it's even supposed to work when opening a level instead of streaming it.

**Comment by muit** [comment]
Wow, thank you for the detailed report. It will be very helpful.
Mega works for me :)

**Comment by muit** [comment]
Btw, thank you very much for the test project @ReiMari. It was super helpful
