### ISSUE TITLE
Not working in packaged game.

### ISSUE THREAD

**Issue by seddonmb** [PipeRift/SaveExtension#29]
Attempts to save always crash, but only in a packaged game.  works fine in the Editor.

4.21.2
plugin ver 1.2

**Comment by muit** [comment]
Hi @seddonmb  is this crash the same as #30?

If not, could you provide us with a log?
Thanks

**Comment by seddonmb** [comment]
Hi,

I suspect it's the same as #30.  I think because changing async to sync in
default gets reset back to async, this is packaging as async.

If async worked, this wouldn't be an issue.

If the default was changed, it wouldn't be an issue.

Ultimately though it would be nice if async worked and/or changes to
presets didn't reset to default.

Mark

**Comment by kbbits** [comment]
Rather than opening a new issue, I'm commenting here.
I've created a project that you can reproduce this issue as well as issues: #25 , #30 & #34.
https://github.com/kbbits/SaveExtentionTest_2
Note: this project has C++ code -- just a few structs for DataTable use.

This particular issue is now a roadblock for progress in my project.
To repro #29 : 
 - clone git project, open it in UE4 editor. (let it build, etc.)
 - Set SaveExtention preferences to:  
     -- Uncheck Auto save, Uncheck Auto load.  Check Debug option in advanced prefs.  
     -- Set all three sync options to "Only Synch".
 - Package project. In my tests it was for Windows 64-bit.
 - After packaging completes, locate the packaged SETest_2.exe, right-click -> Run as Administrator.
 - When game starts, hit "b" key to spawn a ball in the persistent level. (yellow ball)
 - Hit "k" key to save.  This should work.
 - Walk up onto labeled platform on the left.  This will load Sublevel_2.
 - Walk back down to ground floor.
 - Hit "k" key to save -->  Crash.
If you repeat the steps above but unload Sublevel_2 (by stepping on the unload trigger) before doing the final save, the game saves with no error/crash.

To repro #34 (actors in sublevel): 
 - open project in editor.
 - Run PIE in new editor window.
 - Hit "b" to spawn ball in persistent level (yellow ball)
 - Walk up to sublevel 1 platform. (HUD will indicate Sublevel_1)
 - Hit "b" to spawn in Sublevel_1, green ball (this sublevel is not streamed, it's always loaded)
 - Walk up to top sublevel 2 platform (HUD will indicate Sublevel_2)
 - Hit "b" to spawn a ball in Sublevel_2 (red ball). 
 - Walk down to ground.
 - Hit "k" to save game.
 - Exit game (left-shift+x)
After the steps above proceed to Scenario 1 or Scenario 2.
 Scenario 1:
    - Start game again in new PIE.
    - Walk up stairs to trigger loading of sublevel_2.
    - Hit "l" to load game.
    - Note persistent and sublevel_1 actors are loaded. (yellow and green balls) 
    - Note that sublevel_2, already streamed in, is still visible and red ball is correctly loaded from save.
    - All seems correct with this scenario.
 Scenario 2:
    - Start game again in new PIE.
    - Hit "l" to load game.
    - Note persistent and sublevel_1 actors are loaded. (yellow and green balls) 
    - Note that sublevel_2 is not streamed in nor visible.
    - Walk up stairs to load sublevel_2.
    - Note that the red ball (spawned into sublevel_2) is not present - this is a problem.
    - Hit "l" to load game.
    - Note that sublevel_2 was already loaded(streamed), and now the game load did re-load the sublevel_2 actor (the red ball).

**Comment by muit** [comment]
Hi!
1.4 includes many fixes including not saving in packaged games and multithreading crashes.
Closing for tracking.

Thank you very much for the detailed reports!
They really help!

Muit
