### ISSUE TITLE
Wiping arrays after loading.

### ISSUE THREAD

**Issue by AngeredOne** [PipeRift/SaveExtension#37]
Hi there.

I save PlayerController and UserType Component(ActorComponent) on it.
They both have array of UserType(Car). On runtime i may add some elements in that arrays, then save and try to load. After loading all arrays data is wipe out. 

 - Engine Version: 4.22.1
 - Plugin Version: 1.2(last).
 - OS: Linux

**Comment by muit** [comment]
Is that array made of blueprint structs?
If true, then know blueprint structs cant be saved until 4.23 (#4 )

**Comment by AngeredOne** [comment]
> If true, then know blueprint structs cant be saved until 4.23 (#4 )

No, user type is... We just create c++ type, which inherite UObject. We call it "constructable type', becouse UE do not have same by default. 
I also can mark array as "SaveGame".

**Comment by muit** [comment]
Hi @AngeredOne,
Saving subobjects is not supported at the moment.

This is due to the complexity on reference counting of the garbage collector and UPROPERTY pointers.

If you still want this feature feel free to post it as a feature. That way we can know what you need exactly and if possible, implement it.

Thanks,
muit
