### ISSUE TITLE
Destroy Actor Breaks load function

### ISSUE THREAD

**Issue by DeadlyHit** [PipeRift/SaveExtension#6]
https://puu.sh/CliRp/a990f27263.mp4
A video of what happens

How to reproduce this

So my game currently has a death state that when you die the Actor is destroyed
So I set up on the death screen to show a Load from ID basically a checkpoint system
https://puu.sh/Clj26/42336d7379.png
I think this should be enough to show you whats happening if not msg me on Discord @DeadlyHit for more info

**Comment by muit** [comment]
Thanks for reporting it! Will report back when I have news

**Comment by muit** [comment]
As a preliminary hint of what may be happening, Saving and Loading is by default asynchronous. If you instantly delete your actor, it will not report back and could even fail.

The save system also takes care of all actors's lifetime. If you create actors after saving when you load they will be deleted, because at the time of saving they didn't exist. This applies to the player as well, unless you modify its saving settings.

Let me know if this worked for you, or if you were able to fix it otherway.
For tracking purposes I will close the issue (and will open it if needed).
