### ISSUE TITLE
Saving crashes the game

### ISSUE THREAD

**Issue by Worlfy** [PipeRift/SaveExtension#7]
**Describe the bug**
Using the save function 99% of the time crashes the engine, this happens 100% when using "Get Save Manager" > "Save Slot to Id"

![image](https://user-images.githubusercontent.com/8803519/50386846-6b614d00-06ef-11e9-9a93-c457e37fafd3.png)

**Logs**
I unfortunately can't find an error

**Environment (please complete the following information):**
 - Engine Version: 4.21.1
 - Plugin Version: 1.0d
 - OS: Windows 10

**Comment by muit** [comment]
Thanks for the report, I will try to reproduce it soon :)

**Comment by Worlfy** [comment]
Any other information I could give you? Would custom BPs cause issues?

**Comment by muit** [comment]
mm I don't think so, I use Blueprints all the time :(
Since you said logs didn't show anything of much interest I asked for a demo project.

If you are worried about it being public, feel free to email it to me at info@piperift.com
Otherway, we can still try, but there are not many hints here that I can use without propper debugging.

**Comment by muit** [comment]
Closing for tracking purposes.
Feel free to comment for new information.
Thanks!
